#!/bin/bash -e

# Usage: /sbin/backup

source /container/run/environment.sh

# delete backups that are over $MMC_MAIL_BACKUP_TTL days
find $BACKUP_OUTPUT -type f -mtime +$BACKUP_TTL -exec rm {} \;

# Date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"
backupFilePath="$BACKUP_OUTPUT/$(date "$dateFileFormat").tar.gz"

tar -czf $backupFilePath $BACKUP_INPUT
chmod 600 $backupFilePath

exit 0
